aiosmtpd==1.3.1; python_version<="3.9"
aiosmtpd==1.4.0; python_version>="3.10"
cryptography==3.4.4; python_implementation!="PyPy"
cryptography==3.4.4; python_implementation=="PyPy" and python_version<="3.7"
cryptography==36.0.0; python_implementation=="PyPy" and python_version=="3.8"
cryptography==38.0.3; python_implementation=="PyPy" and python_version>="3.9" # To fix a security issue with 37.0.0 to 38.0.2
pytest==6.2.0; python_version<="3.9"
pytest==6.2.5; python_version>="3.10"  # Due to an error with assertion rewrites under 3.10
python-dotenv==0.8.0
# Test fixtures
pytest-asyncio==0.10.0; python_version<="3.7"
pytest-asyncio==0.11.0; python_version>="3.8"
pytest-timeout==1.0.0
